### ISSUE TITLE
把10_ipv4_outbounds.json改成单独的 z_direct_outbound.json/wireguard_out_IPv6.json之后，分流似乎失效了

### ISSUE THREAD

**Issue by BallM8964** [mack-a/v2ray-agent#981]
## 1.问题描述
10_ipv4_outbounds.json改成单独的 z_direct_outbound.json/wireguard_out_IPv6.json之后，分流似乎失效了
包括ipv6分流经常报错，而且卸载ipv6分流以后在09_routing.json里面还是会存在
## 2.安装失败的log或者截图
cat /etc/v2ray/xray/access.log |grep blackhole
cat /etc/v2ray/xray/access.log |grep wire
的结果都是没有，这是不可能的，分流域名和个别遗留的cn黑洞域名一般会出现。

## 3.系统版本
Ubuntu20.04
## 4.脚本版本
3.2.24-3.2.28

**Comment by mack-a** [comment]
**改成单独的 z_direct_outbound.json/wireguard_out_IPv6.json之后** 这句是什么意思，是自己手动修改吗？
IPv6分流经常报错有具体的复现步骤吗？

**Comment by BallM8964** [comment]
![image](https://github.com/mack-a/v2ray-agent/assets/59858578/4c41717f-774e-45ed-be0f-9daa9e9acc4c)
这是以前安装的正常的，通过5 Reality管理安装的。xray-core


![image](https://github.com/mack-a/v2ray-agent/assets/59858578/b48486d5-b32d-4818-aafb-7f1104eadc17)
这是 新安装的，通过2-1-7 7.VLESS+Reality+uTLS+Vision[推荐] 安装的。xray-core
这个安装还会默认把nginx装上，在80端口。

新版本的就不是使用10_ipv4_outbounds.json文件，而是默认走z_direct_outbound.json文件，添加一个wireguard v6分流会再生成一个wireguard_out_IPv6.json文件，同样黑洞会产生一个blackhole.json文件，但是这个方法的分流/黑洞并不起效果，在accesss.log里面一条记录都找不到。

**Comment by Xunflash** [comment]
同样的问题，现在全新安装的分流压根就不生效，不清楚啥问题，access.log里面全是走的z_direct_outbound这个配置，而且还有个问题，设置全局warp分流之后再卸载warp全局分流不会重新生成z_direct_outbound.json和9_routing.json,导致配置直接炸掉无法连接

**Comment by mack-a** [comment]
https://github.com/mack-a/v2ray-agent/releases/tag/v3.2.30 

@Xunflash 你的问题修复了，剩下的未复现。建议卸载后重新尝试或者复述详细复现步骤。

**Comment by Xunflash** [comment]
> 建议卸载后重新尝试或者复述详细复现步骤。
install.log:
`Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.net
 * elrepo-kernel: ftp.yz.yamagata-u.ac.jp
 * epel: ftp.riken.jp
 * extras: mirrors.cat.net
 * updates: mirrors.cat.net
Resolving Dependencies
--> Running transaction check
---> Package docker-buildx-plugin.x86_64 0:0.13.0-1.el7 will be updated
---> Package docker-buildx-plugin.x86_64 0:0.13.1-1.el7 will be an update
---> Package docker-ce.x86_64 3:25.0.4-1.el7 will be updated
---> Package docker-ce.x86_64 3:25.0.5-1.el7 will be an update
---> Package docker-ce-cli.x86_64 1:25.0.4-1.el7 will be updated
---> Package docker-ce-cli.x86_64 1:25.0.5-1.el7 will be an update
---> Package docker-ce-rootless-extras.x86_64 0:25.0.4-1.el7 will be updated
---> Package docker-ce-rootless-extras.x86_64 0:25.0.5-1.el7 will be an update
---> Package docker-compose-plugin.x86_64 0:2.24.7-1.el7 will be updated
---> Package docker-compose-plugin.x86_64 0:2.25.0-1.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                     Arch     Version          Repository          Size
================================================================================
Updating:
 docker-buildx-plugin        x86_64   0.13.1-1.el7     docker-ce-stable    14 M
 docker-ce                   x86_64   3:25.0.5-1.el7   docker-ce-stable    26 M
 docker-ce-cli               x86_64   1:25.0.5-1.el7   docker-ce-stable    14 M
 docker-ce-rootless-extras   x86_64   25.0.5-1.el7     docker-ce-stable   9.4 M
 docker-compose-plugin       x86_64   2.25.0-1.el7     docker-ce-stable    13 M

Transaction Summary
================================================================================
Upgrade  5 Packages

Total download size: 76 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
--------------------------------------------------------------------------------
Total                                               41 MB/s |  76 MB  00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : docker-compose-plugin-2.25.0-1.el7.x86_64                   1/10 
  Updating   : docker-buildx-plugin-0.13.1-1.el7.x86_64                    2/10 
  Updating   : 1:docker-ce-cli-25.0.5-1.el7.x86_64                         3/10 
  Updating   : docker-ce-rootless-extras-25.0.5-1.el7.x86_64               4/10 
  Updating   : 3:docker-ce-25.0.5-1.el7.x86_64                             5/10 
  Cleanup    : 3:docker-ce-25.0.4-1.el7.x86_64                             6/10 
  Cleanup    : docker-ce-rootless-extras-25.0.4-1.el7.x86_64               7/10 
  Cleanup    : 1:docker-ce-cli-25.0.4-1.el7.x86_64                         8/10 
  Cleanup    : docker-buildx-plugin-0.13.0-1.el7.x86_64                    9/10 
  Cleanup    : docker-compose-plugin-2.24.7-1.el7.x86_64                  10/10 
  Verifying  : 1:docker-ce-cli-25.0.5-1.el7.x86_64                         1/10 
  Verifying  : docker-ce-rootless-extras-25.0.5-1.el7.x86_64               2/10 
  Verifying  : 3:docker-ce-25.0.5-1.el7.x86_64                             3/10 
  Verifying  : docker-buildx-plugin-0.13.1-1.el7.x86_64                    4/10 
  Verifying  : docker-compose-plugin-2.25.0-1.el7.x86_64                   5/10 
  Verifying  : docker-compose-plugin-2.24.7-1.el7.x86_64                   6/10 
  Verifying  : docker-buildx-plugin-0.13.0-1.el7.x86_64                    7/10 
  Verifying  : docker-ce-rootless-extras-25.0.4-1.el7.x86_64               8/10 
  Verifying  : 1:docker-ce-cli-25.0.4-1.el7.x86_64                         9/10 
  Verifying  : 3:docker-ce-25.0.4-1.el7.x86_64                            10/10 

Updated:
  docker-buildx-plugin.x86_64 0:0.13.1-1.el7                                    
  docker-ce.x86_64 3:25.0.5-1.el7                                               
  docker-ce-cli.x86_64 1:25.0.5-1.el7                                           
  docker-ce-rootless-extras.x86_64 0:25.0.5-1.el7                               
  docker-compose-plugin.x86_64 0:2.25.0-1.el7                                   

Complete!
`
安装步骤：
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/eb6833e3-d577-4af0-ac2d-7bda2a2e4d50)
conf文件夹内容
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/bec54c3c-b3f4-4de0-b39a-c7a524c3d416)
是我操作哪里有问题吗，结果还是无法正常分流到
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/62a8e037-5a21-4406-8caa-e458eca09355)

**Comment by mack-a** [comment]
我卸载后用最新脚本完全按照你提供的步骤进行分流，没有复现你的问题。打开trace测试 warp=on。

**Comment by BallM8964** [comment]
warp ipv6分流，写两个域名就会崩溃，脚本已经升级到3.2.31

**Comment by Xunflash** [comment]
> 我卸载后用最新脚本完全按照你提供的步骤进行分流，没有复现你的问题。打开trace测试 warp=on。 @Xunflash
我重新装了一台debian测试还是一样，而且提示未安装warp分流
![image](https://github.com/mack-a/v2ray-agent/assets/71567536/27a1a6c0-0601-49bb-9261-0406886e4626)

**Comment by mack-a** [comment]
> 3.2.31，新问题，例如我添加了黑洞CN，再添加ipv6分流，就覆盖掉了黑洞，只剩下ipv6; 反过来先添加ipv6分流再添加黑洞CN就正常。

如果使用全局分流会覆盖所有内容，我考虑一下这里保留域名黑名单是否有必要。

**Comment by mack-a** [comment]
> > 我卸载后用最新脚本完全按照你提供的步骤进行分流，没有复现你的问题。打开trace测试 warp=on。 @Xunflash
> 
> 我重新装了一台debian测试还是一样，而且提示未安装warp分流 ![image](https://private-user-images.githubusercontent.com/71567536/314431467-27a1a6c0-0601-49bb-9261-0406886e4626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Mjc3MjYsIm5iZiI6MTcxMDkyNzQyNiwicGF0aCI6Ii83MTU2NzUzNi8zMTQ0MzE0NjctMjdhMWE2YzAtMDYwMS00OWJiLTkyNjEtMDQwNjg4NmU0NjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NTE5NDU1YmFlYmYzNDMxNWJlMzVkMDE2YTNhMDEzYjBhMmRhZjNhYmYzODI3NGQ1NmZhY2M5ZWNmNzE3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chpY1GOHeGlulvbc7x5GZL8p23nCYDFTGBl6um5qdFE)
> 
> 我加了个输出路径调试了下，好像是跑到下面的else里面去了... ![image](https://private-user-images.githubusercontent.com/71567536/314433581-d6d342ce-a3db-4211-a256-05a3258b5a2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5Mjc3MjYsIm5iZiI6MTcxMDkyNzQyNiwicGF0aCI6Ii83MTU2NzUzNi8zMTQ0MzM1ODEtZDZkMzQyY2UtYTNkYi00MjExLWEyNTYtMDVhMzI1OGI1YTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMDcyMDE2MGFkMjE1ZmQ0OGNjZGI1NDExNWE3ZGQ3YjRlMTE4YTRmNTQxYjVhYjkwMGM3OTMyODY3MDEwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-h71ijLChGmXFDXERDUckloN-dL34gY_E2Ld9-QNlPg)

**v3.2.32已修复**

**Comment by mack-a** [comment]
@Xunflash 你的另一个未复现问题，你可以另开一个issue。

**Comment by BallM8964** [comment]
> 后再卸载warp全局分流不会重新生成z_direct_

没有更改设置warp全局分流选项，就是安装好，直接11分流，2 warp IPv6分流，添加域名。
而且添加域名经常会崩溃出错，见下面的记录。
-------------------------------------------------------------
请选择:2
# 注意事项
# 支持sing-box、Xray-core
# 使用教程：https://www.v2ray-agent.com/archives/1683226921000

请按照上面示例录入域名:alibaba
 ---> 添加完毕
 ---> Xray关闭成功
Xray启动失败
请手动执行以下的命令后【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】将错误日志进行反馈
root@vmhk-intl-001:/etc/v2ray-agent/xray# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.8.9 (Xray, Penetrates Everything.) 37f8654 (go1.22.1 linux/amd64)
A unified platform for anti-censorship.
2024/03/20 10:39:01 Using confdir from arg: /etc/v2ray-agent/xray/conf
Failed to start: main: failed to load config files: [/etc/v2ray-agent/xray/conf/00_log.json /etc/v2ray-agent/xray/conf/07_VLESS_vision_reality_inbounds.json /etc/v2ray-agent/xray/conf/08_VLESS_vision_gRPC_inbounds.json /etc/v2ray-agent/xray/conf/09_routing.json /etc/v2ray-agent/xray/conf/11_dns.json /etc/v2ray-agent/xray/conf/12_policy.json /etc/v2ray-agent/xray/conf/IPv6_out.json /etc/v2ray-agent/xray/conf/blackhole_out.json /etc/v2ray-agent/xray/conf/wireguard_out_IPv6.json /etc/v2ray-agent/xray/conf/z_direct_outbound.json] > infra/conf/serial: failed to decode config: /etc/v2ray-agent/xray/conf/wireguard_out_IPv6.json > infra/conf/serial: failed to read config file at line 20 char 21 > invalid character ',' looking for beginning of value
